import { validateContent, type Effect, type MetricKey } from './index.js';

const fx = (
  key: MetricKey,
  amount: number,
  timing: Effect['timing'],
  label: string,
  theoryId: string,
): Effect => ({
  key,
  amount,
  timing,
  label,
  theoryId,
});

export const sampleContent = validateContent({
  contentVersion: 'slice-0.1.0',
  engineVersion: '0.1.0',
  theories: [
    {
      theoryId: 't-segment',
      title: '不是所有人',
      explanation: '品牌要先决定为谁服务。',
      transferPrompt: '你的作业对象是谁？',
    },
    {
      theoryId: 't-promise',
      title: '承诺债务',
      explanation: '说出口的承诺会变成之后必须交付的成本。',
      transferPrompt: '你的视觉和产品能交付同一件事吗？',
    },
    {
      theoryId: 't-identity',
      title: '视觉是经营变量',
      explanation: '识别、适配和文化可信度会影响经营结果。',
      transferPrompt: '你的视觉方案如何进入真实触点？',
    },
    {
      theoryId: 't-growth',
      title: '增长的代价',
      explanation: '注意力增长可能放大信任和交付问题。',
      transferPrompt: '如果明天突然火了，你能交付吗？',
    },
  ],
  rounds: [
    {
      roundId: 'r01',
      chapterId: 'c1',
      title: '先别急着做 Logo',
      openingScene: '老街拐角有一间空铺子。房东说，游客会拍照，但没人知道为什么要回来。',
      goal: '确定第一批真正要服务的人。',
      evidence: [
        {
          evidenceId: 'ev-r01-footfall',
          title: '一周客流观察',
          body: '周末游客多，工作日附近居民更稳定；两类人的停留和购买理由不同。',
          cost: 8,
          theoryIds: ['t-segment'],
        },
      ],
      choices: [
        {
          choiceId: 'r01-local',
          label: '先做附近居民的日常茶饮',
          temptation: '复购慢，但可以慢慢建立关系。',
          statedBenefit: '更容易形成稳定习惯。',
          statedConcern: '开头不够热闹。',
          effects: [
            fx('segmentFit', 10, 'immediate', '目标更聚焦', 't-segment'),
            fx('trust', 5, 'delayed', '熟客信任积累', 't-segment'),
            fx('awareness', -3, 'immediate', '声量起步较慢', 't-segment'),
          ],
          conditions: [],
          consequenceText: '店里没有立刻排长队，但几位附近住户开始记住了你。',
          theoryIds: ['t-segment'],
        },
        {
          choiceId: 'r01-tourist',
          label: '做一个所有游客都想拍的地标饮品',
          temptation: '照片传播很快，朋友会说你有想象力。',
          statedBenefit: '迅速获得注意力。',
          statedConcern: '游客未必会再次购买。',
          effects: [
            fx('awareness', 12, 'immediate', '获得第一波注意力', 't-segment'),
            fx('segmentFit', -6, 'delayed', '服务对象变得模糊', 't-segment'),
            fx('conversion', 4, 'immediate', '尝鲜购买增加', 't-segment'),
          ],
          conditions: [],
          consequenceText: '第一批游客拍了照，但店员开始回答“这杯到底给谁喝”。',
          theoryIds: ['t-segment'],
        },
      ],
      visualTests: [],
      visualRequired: false,
      eventIds: ['e-r01-rain'],
      theoryIds: ['t-segment'],
    },
    {
      roundId: 'r05',
      chapterId: 'c2',
      title: '你说的品牌做得到吗',
      openingScene: '你想把品牌说成“慢下来喝一杯”。供应商却提醒：你的外带窗口只有两分钟出杯。',
      goal: '让品牌承诺和产品交付互相支持。',
      evidence: [
        {
          evidenceId: 'ev-r05-queue',
          title: '午间排队记录',
          body: '高峰期平均等待 6 分钟；最受欢迎的两款饮品制作步骤不同。',
          cost: 10,
          theoryIds: ['t-promise'],
        },
      ],
      choices: [
        {
          choiceId: 'r05-simplify',
          label: '删掉复杂款，先把稳定交付做好',
          temptation: '菜单看起来没那么“丰富”。',
          statedBenefit: '承诺更容易兑现。',
          statedConcern: '少了一些炫技空间。',
          effects: [
            fx('productDelivery', 12, 'immediate', '出杯稳定性提高', 't-promise'),
            fx('promiseCredibility', 9, 'delayed', '慢下来不再只是文案', 't-promise'),
            fx('awareness', -2, 'immediate', '话题款减少', 't-promise'),
          ],
          conditions: [],
          consequenceText: '客人不再问“为什么等这么久”，但菜单墙变得安静了一点。',
          theoryIds: ['t-promise'],
        },
        {
          choiceId: 'r05-promise',
          label: '保留全菜单，用“慢工”解释等待',
          temptation: '一句漂亮的话就能保护你现在的创意。',
          statedBenefit: '品牌故事更完整。',
          statedConcern: '等待可能变成不守时。',
          effects: [
            fx('brandConsistency', 6, 'immediate', '叙事更完整', 't-promise'),
            fx('productDelivery', -8, 'delayed', '复杂流程继续拖慢交付', 't-promise'),
            fx('reputationDebt', 10, 'delayed', '解释变成承诺债务', 't-promise'),
          ],
          conditions: [],
          consequenceText: '有人愿意等，也有人说：慢不是问题，没说清楚才是。',
          theoryIds: ['t-promise'],
        },
      ],
      visualTests: [],
      visualRequired: false,
      eventIds: ['e-r05-review'],
      theoryIds: ['t-promise'],
    },
    {
      roundId: 'r08',
      chapterId: 'c3',
      title: '设计进入现实',
      openingScene: '设计师递来三套视觉提案：一套很古雅，一套很醒目，一套像街坊手写的招呼。',
      goal: '选择能在真实触点中工作的视觉系统。',
      evidence: [
        {
          evidenceId: 'ev-r08-street',
          title: '街景观察',
          body: '招牌在窄街中常被遮挡；外带杯会被带到手机照片和办公室桌面上。',
          cost: 12,
          theoryIds: ['t-identity'],
        },
      ],
      choices: [
        {
          choiceId: 'r08-system',
          label: '优先选择能缩小、能延展的识别系统',
          temptation: '它没有最强的第一眼戏剧性。',
          statedBenefit: '招牌、杯套和头像更统一。',
          statedConcern: '可能不够“出片”。',
          effects: [
            fx('visualRecognition', 9, 'immediate', '识别基础更稳', 't-identity'),
            fx('visualAdaptability', 12, 'delayed', '触点延展更顺', 't-identity'),
            fx('brandConsistency', 8, 'delayed', '视觉和承诺更一致', 't-identity'),
          ],
          conditions: [],
          consequenceText: '第一眼没有尖叫，但杯子离开老街后仍然像是你的。',
          theoryIds: ['t-identity'],
        },
        {
          choiceId: 'r08-symbol',
          label: '优先选择最有地方符号感的方案',
          temptation: '大家一看就知道“这是黄山”。',
          statedBenefit: '文化识别很快建立。',
          statedConcern: '可能和隔壁店撞车。',
          effects: [
            fx('culturalCredibility', 4, 'immediate', '文化联想变强', 't-identity'),
            fx('visualRecognition', 10, 'immediate', '街景中更醒目', 't-identity'),
            fx('differentiation', -7, 'delayed', '同质化风险上升', 't-identity'),
          ],
          conditions: [],
          consequenceText: '游客说“很有黄山味”，你却发现三家店都在用同一座山。',
          theoryIds: ['t-identity'],
        },
      ],
      visualTests: [
        {
          testId: 'sign_3_second',
          title: '店招三秒测试',
          prompt: '路人经过时，能否在三秒内认出店名和品类？',
          theoryIds: ['t-identity'],
        },
        {
          testId: 'mobile_shrink',
          title: '手机缩小测试',
          prompt: '缩成社交头像后，识别还剩多少？',
          theoryIds: ['t-identity'],
        },
        {
          testId: 'competitor_comparison',
          title: '同街竞争测试',
          prompt: '与同街视觉并置后，是否仍有自己的位置？',
          theoryIds: ['t-identity'],
        },
        {
          testId: 'packaging_stress',
          title: '包装使用测试',
          prompt: '杯套沾水、折叠、离开老街后还能工作吗？',
          theoryIds: ['t-identity'],
        },
      ],
      visualRequired: true,
      eventIds: ['e-r08-collision'],
      theoryIds: ['t-identity'],
    },
    {
      roundId: 'r11',
      chapterId: 'c4',
      title: '火了以后全是事',
      openingScene: '一条短视频让店门口排起了队。外卖平台来谈合作，老客却说自己进不去了。',
      goal: '决定增长是否要超过当前组织的交付能力。',
      evidence: [
        {
          evidenceId: 'ev-r11-capacity',
          title: '供应和服务盘点',
          body: '原料供应可以支撑约 1.5 倍订单，但培训和店内动线还没有准备好。',
          cost: 14,
          theoryIds: ['t-growth'],
        },
      ],
      choices: [
        {
          choiceId: 'r11-grow',
          label: '趁热扩大线上渠道',
          temptation: '现在不接，平台就会找别人。',
          statedBenefit: '知名度和订单快速增长。',
          statedConcern: '服务体验会被放大检验。',
          effects: [
            fx('awareness', 15, 'immediate', '声量迅速放大', 't-growth'),
            fx('channelDependence', 12, 'delayed', '平台依赖加深', 't-growth'),
            fx('orgCapacity', -10, 'delayed', '组织承压', 't-growth'),
            fx('reputationDebt', 8, 'delayed', '负面体验扩散', 't-growth'),
          ],
          conditions: [],
          consequenceText: '订单像潮水一样来，评论区也开始讨论“排队是否值得”。',
          theoryIds: ['t-growth'],
        },
        {
          choiceId: 'r11-steady',
          label: '先限量，把老客体验稳住',
          temptation: '你会错过一次漂亮的增长曲线。',
          statedBenefit: '信任和交付能力同步积累。',
          statedConcern: '外界可能觉得你不够野心。',
          effects: [
            fx('trust', 8, 'immediate', '老客感到被看见', 't-growth'),
            fx('orgCapacity', 8, 'delayed', '组织能力获得缓冲', 't-growth'),
            fx('awareness', -4, 'immediate', '扩散速度放慢', 't-growth'),
            fx('loyalty', 8, 'delayed', '社区关系更稳', 't-growth'),
          ],
          conditions: [],
          consequenceText: '你没有接住所有订单，但留下的人开始替你解释为什么值得等。',
          theoryIds: ['t-growth'],
        },
      ],
      visualTests: [],
      visualRequired: false,
      eventIds: ['e-r11-queue'],
      theoryIds: ['t-growth'],
    },
  ],
  events: [
    {
      eventId: 'e-r01-rain',
      title: '老街突然下雨',
      body: '雨把游客赶进店里，也让没有遮雨动线的门口变得拥挤。',
      conditions: [],
      probability: 60,
      effects: [
        fx('conversion', 4, 'immediate', '临时进店增加', 't-segment'),
        fx('trust', -2, 'delayed', '动线混乱留下印象', 't-segment'),
      ],
      classWide: true,
      once: true,
      theoryIds: ['t-segment'],
    },
    {
      eventId: 'e-r05-review',
      title: '一条很诚实的评价',
      body: '顾客说：味道不错，但“慢下来”不是让我等十分钟。',
      conditions: [{ type: 'metric_at_most', key: 'productDelivery', value: 55 }],
      probability: 100,
      effects: [
        fx('trust', -5, 'immediate', '承诺被重新审视', 't-promise'),
        fx('reputationDebt', 5, 'delayed', '解释成本增加', 't-promise'),
      ],
      classWide: false,
      once: true,
      theoryIds: ['t-promise'],
    },
    {
      eventId: 'e-r08-collision',
      title: '隔壁也换了山形标',
      body: '同街新店用了相似符号。顾客问：你们是不是同一家？',
      conditions: [{ type: 'metric_at_most', key: 'differentiation', value: 45 }],
      probability: 100,
      effects: [
        fx('awareness', -3, 'immediate', '识别混淆', 't-identity'),
        fx('differentiation', -5, 'delayed', '同质化成本增加', 't-identity'),
      ],
      classWide: false,
      once: true,
      theoryIds: ['t-identity'],
    },
    {
      eventId: 'e-r11-queue',
      title: '排队变成了景点',
      body: '有人专门来排队拍照，也有人拍完照就走。',
      conditions: [{ type: 'metric_at_least', key: 'awareness', value: 55 }],
      probability: 70,
      effects: [
        fx('awareness', 8, 'immediate', '排队带来可见性', 't-growth'),
        fx('trust', -4, 'delayed', '体验差异被放大', 't-growth'),
      ],
      classWide: true,
      once: true,
      theoryIds: ['t-growth'],
    },
  ],
  visualSystems: [
    {
      visualId: 'v-system',
      name: '一笔成街',
      description: '用连续线条建立可缩放、可延展的识别系统。',
      attributes: {
        recognitionStrength: 72,
        smallSizeLegibility: 86,
        storefrontDistinctiveness: 64,
        packagingRobustness: 78,
        culturalCredibility: 70,
        brandConsistency: 88,
        touchpointAdaptability: 90,
        productionCost: 55,
      },
      touchpoints: ['storefront', 'cup', 'packaging', 'avatar'],
    },
    {
      visualId: 'v-symbol',
      name: '山影入杯',
      description: '把地方山形和茶饮容器结合，第一眼地域联想很强。',
      attributes: {
        recognitionStrength: 82,
        smallSizeLegibility: 62,
        storefrontDistinctiveness: 84,
        packagingRobustness: 65,
        culturalCredibility: 78,
        brandConsistency: 68,
        touchpointAdaptability: 58,
        productionCost: 62,
      },
      touchpoints: ['storefront', 'cup', 'packaging', 'avatar'],
    },
    {
      visualId: 'v-hand',
      name: '街坊手写',
      description: '像邻里招呼一样亲切，依靠语气和手写变化建立关系。',
      attributes: {
        recognitionStrength: 62,
        smallSizeLegibility: 70,
        storefrontDistinctiveness: 68,
        packagingRobustness: 72,
        culturalCredibility: 82,
        brandConsistency: 76,
        touchpointAdaptability: 74,
        productionCost: 45,
      },
      touchpoints: ['storefront', 'cup', 'packaging', 'avatar'],
    },
  ],
  endings: [
    {
      endingId: 'e-loyal',
      title: '小众忠诚社群',
      description: '规模不喧闹，但人们愿意带朋友回来。',
      conditions: [{ type: 'metric_at_least', key: 'loyalty', value: 55 }],
      priority: 20,
    },
    {
      endingId: 'e-flow',
      title: '高知名度低信任的流量品牌',
      description: '所有人都听过，真正愿意留下的人却不多。',
      conditions: [
        { type: 'metric_at_least', key: 'awareness', value: 65 },
        { type: 'metric_at_most', key: 'trust', value: 42 },
      ],
      priority: 30,
    },
    {
      endingId: 'e-balanced',
      title: '稳定大众品牌',
      description: '没有一个惊天动地的选择，但每个环节都能互相托住。',
      conditions: [],
      priority: 1,
    },
  ],
  conceptCards: [
    {
      conceptId: 'c-segment',
      title: '不是所有人',
      explanation: '聚焦不是放弃市场，而是让承诺有对象。',
      sourceTheoryId: 't-segment',
      unlockTag: 'segment_decided',
    },
    {
      conceptId: 'c-promise',
      title: '承诺债务',
      explanation: '每一句品牌话都可能变成未来的交付账单。',
      sourceTheoryId: 't-promise',
      unlockTag: 'promise_tested',
    },
    {
      conceptId: 'c-visual',
      title: '视觉是经营变量',
      explanation: '招牌、杯套和包装会继续替你的品牌说话。',
      sourceTheoryId: 't-identity',
      unlockTag: 'visual_tested',
    },
    {
      conceptId: 'c-growth',
      title: '增长的代价',
      explanation: '声量放大以后，问题也会被更多人看见。',
      sourceTheoryId: 't-growth',
      unlockTag: 'growth_event',
    },
  ],
  achievements: [
    {
      achievementId: 'a-first-focus',
      title: '先问为谁',
      description: '做出第一次明确的目标选择。',
      unlockTag: 'segment_decided',
    },
    {
      achievementId: 'a-kept-promise',
      title: '说到做到',
      description: '让一次品牌承诺和交付能力相互支持。',
      unlockTag: 'promise_tested',
    },
    {
      achievementId: 'a-seen-after-leaving',
      title: '离开老街也认得',
      description: '完成一次视觉触点测试。',
      unlockTag: 'visual_tested',
    },
    {
      achievementId: 'a-growth-choice',
      title: '火了以后再决定',
      description: '在增长压力下做出一次组织选择。',
      unlockTag: 'growth_event',
    },
  ],
});
