import { CONTENT_SCHEMA_VERSION_V11, validateV11Content, type V11Effect } from './v11.js';

const effect = (
  key: V11Effect['key'],
  amount: number,
  timing: V11Effect['timing'],
  label: string,
  theoryId: string,
): V11Effect => ({ key, amount, timing, label, theoryId });

export const v11SliceContent = validateV11Content({
  contentVersion: CONTENT_SCHEMA_VERSION_V11,
  engineVersion: '1.2.0',
  reportVersion: '1.2.0',
  priceBaselineVersion: 'prices-2026-08',
  onboardingSlides: [
    {
      slideId: 'onboarding-situation',
      title: '你的处境',
      body: '你接手了屯溪老街的一间空铺，手里有50万元创业资金和一批地方茶资源。',
      imageKey: 'onboarding-place',
    },
    {
      slideId: 'onboarding-goal',
      title: '一年后怎样算赢',
      body: '店要活下来，顾客愿意购买和回来，产品、形象和服务还要彼此配合。只剩现金或只刷声量都不算赢。',
      imageKey: 'onboarding-goal',
    },
    {
      slideId: 'onboarding-operation',
      title: '每轮都要取舍',
      body: '你可以调查、询价、测试和防范风险，但每轮精力有限。每次决定都会影响之后的经营。',
      imageKey: 'onboarding-operation',
    },
  ],
  victoryConfig: {
    dimensions: [
      { key: 'survival', label: '经营生存', weight: 25 },
      { key: 'customer', label: '顾客资产', weight: 25 },
      { key: 'brand', label: '品牌资产', weight: 30 },
      { key: 'consistency', label: '系统一致性', weight: 20 },
    ],
    successLevel: 'formed_brand',
  },
  metricGlossary: {
    awareness: { label: '知名度', subject: '顾客', explanation: '有多少人注意到这家店。' },
    conversion: { label: '购买转化', subject: '顾客', explanation: '看到产品后愿不愿意买。' },
    trust: { label: '信任', subject: '顾客', explanation: '顾客是否相信你说的承诺。' },
    loyalty: { label: '忠诚与复购', subject: '顾客', explanation: '顾客是否愿意回来并带朋友来。' },
    segmentFit: {
      label: '人群匹配',
      subject: '顾客',
      explanation: '你服务的人和实际到店顾客是否对得上。',
    },
    productDelivery: {
      label: '交付能力',
      subject: '店铺',
      explanation: '产品和服务能否稳定兑现承诺。',
    },
    orgCapacity: { label: '组织承接力', subject: '店铺', explanation: '团队能否接住增长和变化。' },
    differentiation: {
      label: '差异化',
      subject: '店铺',
      explanation: '顾客是否能说清你和别家有什么不同。',
    },
    brandConsistency: {
      label: '品牌一致性',
      subject: '店铺',
      explanation: '产品、话语、视觉和服务是否像在说同一件事。',
    },
    visualRecognition: {
      label: '视觉识别',
      subject: '店铺',
      explanation: '顾客能否在不同地方认出这家店。',
    },
    visualAdaptability: {
      label: '视觉适配',
      subject: '店铺',
      explanation: '视觉能否在店招、包装和小屏上稳定使用。',
    },
    culturalCredibility: {
      label: '文化可信度',
      subject: '店铺',
      explanation: '地方故事是否有真实来源和具体体验支撑。',
    },
    channelDependence: {
      label: '渠道依赖',
      subject: '店铺',
      explanation: '店铺是否过度依赖单一平台或合作渠道。',
    },
    reputationDebt: {
      label: '声誉负债',
      subject: '店铺',
      explanation: '承诺没有及时兑现时，顾客积累的不满。',
    },
  },
  theories: [
    {
      theoryId: 't-segment',
      title: '先决定为谁服务',
      explanation: '品牌不是对所有人说同一句话，而是先找到能够被持续服务的人。',
      transferPrompt: '你的品牌作业具体为谁解决什么问题？',
    },
    {
      theoryId: 't-insight',
      title: '洞察不是一句漂亮话',
      explanation: '调查的价值在于帮助团队理解顾客行为、成本和限制，而不是替团队做决定。',
      transferPrompt: '你的调研证据如何改变了方案比较？',
    },
    {
      theoryId: 't-product',
      title: '产品是承诺的第一现场',
      explanation: '品牌承诺最终要由产品、价格和交付过程兑现。',
      transferPrompt: '你的产品如何证明品牌承诺不是口号？',
    },
    {
      theoryId: 't-identity',
      title: '视觉是经营变量',
      explanation: 'LOGO、VI、包装和门店触点会影响识别、理解、选择和传播。',
      transferPrompt: '你的 LOGO、VI 和包装，分别要解决顾客在哪一步认出你？',
    },
    {
      theoryId: 't-touchpoint',
      title: '系统要在触点中保持一致',
      explanation: '顾客不会只看一张效果图，而会在招牌、杯子、包装和手机页面之间感受品牌。',
      transferPrompt: '你的招牌、杯子和包装，顾客能认出是同一家店吗？',
    },
    {
      theoryId: 't-growth',
      title: '增长会放大组织问题',
      explanation: '声量和订单增长会同时放大交付、团队和关系问题。',
      transferPrompt: '订单多一倍时，哪一步最先需要补人或改流程？',
    },
  ],
  rounds: [
    {
      roundId: 'r01',
      chapterId: 'c1',
      title: '先别急着做 Logo',
      timelineLabel: '第1月上旬',
      isKeyRound: false,
      briefing: {
        situation: '老街拐角有一间空铺子，游客会拍照，但附近居民才是每天经过的人。',
        whyNow: '第一批顾客没有确定，后面的产品、价格和视觉都会摇摆。',
        dilemma: '先服务附近居民，还是先追游客流量？',
        mustComplete: '确定第一批真正要服务的人。',
        imageKey: 'briefing-r01-street',
      },
      actionPointBudget: 8,
      stageActions: [
        {
          actionId: 'r01-observe-footfall',
          actionType: 'research',
          label: '观察不同时段客流',
          description: '记录游客和居民什么时候来、停留多久、为什么购买。',
          cashCostYuan: 0,
          actionPointCost: 1,
          durationDays: 1,
          workload: 1,
          theoryIds: ['t-segment', 't-insight'],
          revealsEvidenceIds: ['ev-r01-footfall', 'ev-r01-competition'],
        },
        {
          actionId: 'r01-interview-neighbors',
          actionType: 'research',
          label: '问问附近住户',
          description: '用一下午听听附近人对日常茶饮的真实期待。',
          cashCostYuan: 800,
          actionPointCost: 2,
          durationDays: 2,
          workload: 2,
          theoryIds: ['t-segment', 't-insight'],
          revealsEvidenceIds: ['ev-r01-neighbor-interviews'],
        },
        {
          actionId: 'r01-quote-rent',
          actionType: 'quote',
          label: '先把开店成本问清楚',
          description: '向房东和供应商确认第一阶段现金压力。',
          cashCostYuan: 500,
          actionPointCost: 1,
          durationDays: 1,
          workload: 1,
          theoryIds: ['t-insight'],
          revealsEvidenceIds: ['ev-r01-opening-cost'],
        },
      ],
      evidence: [
        {
          evidenceId: 'ev-r01-footfall',
          title: '一周客流观察',
          fact: '周末游客多，工作日附近居民更稳定；两类人的停留和购买理由不同。',
          implication: '游客路线容易获得第一波声量，居民路线更有机会形成日常习惯。',
          unknown: '还不知道哪类人愿意复购，也不知道他们愿意接受什么价格。',
          cashCostYuan: 0,
          actionPointCost: 1,
          angle: 'customer',
          relations: [
            {
              targetType: 'choice',
              targetId: 'r01-neighbor',
              relation: 'supports',
              strength: 70,
              explanation: '稳定居民客流支持日常复购路线。',
            },
            {
              targetType: 'choice',
              targetId: 'r01-tourist',
              relation: 'context',
              strength: 55,
              explanation: '周末客流为游客传播路线提供了机会。',
            },
          ],
          theoryIds: ['t-segment', 't-insight'],
        },
        {
          evidenceId: 'ev-r01-competition',
          title: '同街门店观察',
          fact: '相邻门店已经在争夺“来黄山一定要拍”的游客。',
          implication: '单靠醒目不一定形成差异，服务对象需要更具体。',
          unknown: '尚未知道游客会把什么记成你的理由。',
          cashCostYuan: 0,
          actionPointCost: 1,
          angle: 'competition',
          relations: [
            {
              targetType: 'choice',
              targetId: 'r01-tourist',
              relation: 'warns',
              strength: 60,
              explanation: '游客传播路线会直接面对同街竞争。',
            },
          ],
          theoryIds: ['t-segment', 't-insight'],
        },
        {
          evidenceId: 'ev-r01-neighbor-interviews',
          title: '附近住户访谈',
          fact: '十位附近住户大多把“顺手、价格清楚、下次还能喝到同一杯”放在拍照感之前；午后和下班前是他们最常停下的时段。',
          implication:
            '如果先服务居民，产品和服务要先解决日常购买是否省心，而不是只增加第一眼的新鲜感。',
          unknown: '还不知道他们愿意为多丰富的口味和地方故事多付多少钱。',
          cashCostYuan: 800,
          actionPointCost: 2,
          angle: 'customer',
          relations: [
            {
              targetType: 'choice',
              targetId: 'r01-neighbor',
              relation: 'supports',
              strength: 80,
              explanation: '住户把稳定和顺手放在首位，支持先做日常茶饮。',
            },
            {
              targetType: 'choice',
              targetId: 'r01-tourist',
              relation: 'warns',
              strength: 55,
              explanation: '只追求拍照传播，容易忽略居民每天愿不愿意回来。',
            },
          ],
          theoryIds: ['t-segment', 't-insight'],
        },
        {
          evidenceId: 'ev-r01-opening-cost',
          title: '开店成本清单',
          fact: '押金、基础设备和第一批原料会先占住一笔现金；招牌只是开店投入中的一部分。',
          implication: '前期预算要留出产品试做和日常周转，不能把钱只压在看得见的门头上。',
          unknown: '高峰期增加的人手和设备投入，还要在实际经营里继续核算。',
          cashCostYuan: 500,
          actionPointCost: 1,
          angle: 'cost',
          relations: [
            {
              targetType: 'choice',
              targetId: 'r01-tourist',
              relation: 'warns',
              strength: 45,
              explanation: '把预算过早压在强视觉和一次性装饰上，会缩小后续试做空间。',
            },
          ],
          theoryIds: ['t-insight'],
        },
      ],
      choices: [
        {
          choiceId: 'r01-neighbor',
          label: '先做附近居民的日常茶饮',
          summary: '从稳定复购开始建立关系。',
          detail: '先围绕附近住户设计口味、价格和服务节奏，游客可以来，但不作为唯一目标。',
          cashCostYuan: 18000,
          actionPointCost: 3,
          durationDays: 5,
          workload: 3,
          primaryBenefit: '复购基础更稳',
          primaryRisk: '前期声量较慢',
          evidenceRelations: ['ev-r01-footfall', 'ev-r01-neighbor-interviews'],
          effects: [
            effect('segmentFit', 10, 'immediate', '服务对象变清楚了', 't-segment'),
            effect('trust', 5, 'delayed', '熟客信任开始积累', 't-segment'),
          ],
          riskPlanIds: ['risk-r01-repeat'],
          conditions: [],
          theoryIds: ['t-segment'],
          reportExplanation: '聚焦附近居民让后续产品和服务有了明确对象，但需要接受增长较慢。',
          transferPrompt: '你的品牌作业是否明确了第一批真正要服务的人？',
          resultArtKey: 'result-r01-neighbor',
          motionCue: 'counter-warm',
        },
        {
          choiceId: 'r01-tourist',
          label: '做一杯游客都想拍的地标饮品',
          summary: '先用强视觉获得第一波注意力。',
          detail: '把产品做成旅行记忆点，优先考虑拍照、分享和短期客流。',
          cashCostYuan: 26000,
          actionPointCost: 3,
          durationDays: 4,
          workload: 3,
          primaryBenefit: '传播速度更快',
          primaryRisk: '顾客和购买理由容易变模糊',
          evidenceRelations: ['ev-r01-footfall', 'ev-r01-competition'],
          effects: [
            effect('awareness', 12, 'immediate', '第一波注意力来了', 't-segment'),
            effect('conversion', 4, 'immediate', '尝鲜购买增加', 't-segment'),
            effect('segmentFit', -6, 'delayed', '服务对象开始变模糊', 't-segment'),
          ],
          riskPlanIds: [],
          conditions: [],
          theoryIds: ['t-segment', 't-insight'],
          reportExplanation: '游客传播带来快速注意力，但没有自动解决复购和差异化问题。',
          transferPrompt: '你的品牌是因为“好看”被记住，还是因为解决了具体需求？',
          resultArtKey: 'result-r01-tourist',
          motionCue: 'camera-flash',
        },
        {
          choiceId: 'r01-hybrid',
          label: '先做双时段的小范围试卖',
          summary: '用较慢的试验换取更稳的判断。',
          detail: '上午服务居民，下午测试游客产品，用小规模试卖比较两类需求。',
          cashCostYuan: 12000,
          actionPointCost: 4,
          durationDays: 8,
          workload: 4,
          primaryBenefit: '获得更多真实反馈',
          primaryRisk: '时间和精力消耗更大',
          evidenceRelations: ['ev-r01-footfall', 'ev-r01-neighbor-interviews'],
          effects: [
            effect('segmentFit', 6, 'immediate', '两类需求被放在同一张表上比较', 't-insight'),
            effect('conversion', 3, 'immediate', '小范围试卖有反馈', 't-insight'),
            effect('orgCapacity', -4, 'delayed', '团队暂时被试验牵住', 't-insight'),
          ],
          riskPlanIds: [],
          conditions: [],
          theoryIds: ['t-segment', 't-insight'],
          reportExplanation: '小规模试验减少了拍脑袋风险，但需要为学习付出额外时间和组织成本。',
          transferPrompt: '什么时候应该先做小范围验证，而不是立即追求完整发布？',
          resultArtKey: 'result-r01-hybrid',
          motionCue: 'notebook-flip',
        },
      ],
      riskPlans: [
        {
          riskPlanId: 'risk-r01-repeat',
          label: '先做一周复购观察',
          description: '用小范围试卖确认居民是否愿意回来。',
          targetRisk: '复购不足',
          cashCostYuan: 2000,
          actionPointCost: 1,
          mitigationRatio: 30,
          theoryIds: ['t-segment', 't-insight'],
        },
      ],
      visualTests: [],
      visualRequired: false,
      eventIds: [],
      theoryIds: ['t-segment', 't-insight'],
      resultPresentation: {
        resultArtKey: 'result-r01-street',
        motionCue: 'street-light',
        characterReactions: [
          {
            characterId: 'character-ahe',
            text: '先别急着把所有人都叫进来，至少我们知道第一批客人是谁了。',
            conditions: [],
          },
        ],
      },
    },
    {
      roundId: 'r03',
      chapterId: 'c2',
      title: '产品不是品牌的配饰',
      timelineLabel: '第2月',
      isKeyRound: false,
      briefing: {
        situation: '顾客已经等着第一款主打茶饮，但供应商说复杂配方会拖慢出杯。',
        whyNow: '今天决定的产品结构，会同时决定价格、包装和之后的品牌承诺。',
        dilemma: '做一款好传播的复杂产品，还是先做稳定可交付的日常产品？',
        mustComplete: '确定核心产品和它要兑现的承诺。',
        imageKey: 'briefing-r03-product',
      },
      actionPointBudget: 8,
      stageActions: [
        {
          actionId: 'r03-test-recipe',
          actionType: 'test',
          label: '做一轮小样测试',
          description: '比较口味、制作时间和顾客理解成本。',
          cashCostYuan: 3500,
          actionPointCost: 2,
          durationDays: 3,
          workload: 3,
          theoryIds: ['t-product'],
          revealsEvidenceIds: ['ev-r03-queue', 'ev-r03-price'],
        },
        {
          actionId: 'r03-quote-packaging',
          actionType: 'quote',
          label: '询问包装和设备成本',
          description: '先确认复杂产品是否会把成本推到顾客难以接受的区间。',
          cashCostYuan: 800,
          actionPointCost: 1,
          durationDays: 1,
          workload: 1,
          theoryIds: ['t-product'],
          revealsEvidenceIds: ['ev-r03-packaging-cost'],
        },
        {
          actionId: 'r03-negotiate-supply',
          actionType: 'negotiate',
          label: '和供应商谈稳定供货',
          description: '用确定的产品规模换取更稳的原料和交付时间。',
          cashCostYuan: 1200,
          actionPointCost: 2,
          durationDays: 2,
          workload: 2,
          theoryIds: ['t-product'],
          revealsEvidenceIds: ['ev-r03-supply'],
        },
      ],
      evidence: [
        {
          evidenceId: 'ev-r03-queue',
          title: '午间出杯记录',
          fact: '高峰期平均等待 6 分钟，复杂饮品的制作步骤是普通款的两倍。',
          implication: '复杂产品可能提高记忆点，也可能把承诺变成排队成本。',
          unknown: '还不知道顾客愿意为复杂体验多等多久。',
          cashCostYuan: 0,
          actionPointCost: 1,
          angle: 'delivery',
          relations: [
            {
              targetType: 'choice',
              targetId: 'r03-stable',
              relation: 'supports',
              strength: 75,
              explanation: '出杯记录支持先稳定交付的产品路线。',
            },
            {
              targetType: 'choice',
              targetId: 'r03-complex',
              relation: 'warns',
              strength: 70,
              explanation: '复杂款会放大高峰等待风险。',
            },
          ],
          theoryIds: ['t-product'],
        },
        {
          evidenceId: 'ev-r03-price',
          title: '小样顾客反馈',
          fact: '试饮顾客愿意为地方感和新鲜感多付一点，但会把“值得不值得”说给同行的人听。',
          implication: '溢价需要被产品体验和文化解释共同支撑，不能只靠复杂步骤。',
          unknown: '尚未知道离开老街后顾客是否还会主动寻找它。',
          cashCostYuan: 600,
          actionPointCost: 1,
          angle: 'customer',
          relations: [
            {
              targetType: 'choice',
              targetId: 'r03-local-special',
              relation: 'supports',
              strength: 65,
              explanation: '地方感可以支持有理由的轻溢价。',
            },
          ],
          theoryIds: ['t-product', 't-insight'],
        },
        {
          evidenceId: 'ev-r03-packaging-cost',
          title: '包装与设备报价',
          fact: '复杂杯型、定制包装和额外设备会把单杯成本持续推高，销量不够时很难摊平。',
          implication: '好看的包装必须回答“谁愿意为它付钱”，否则会直接挤压产品和服务预算。',
          unknown: '还不知道顾客是否会因为包装而主动复购或推荐。',
          cashCostYuan: 800,
          actionPointCost: 1,
          angle: 'cost',
          relations: [
            {
              targetType: 'choice',
              targetId: 'r03-complex',
              relation: 'warns',
              strength: 70,
              explanation: '复杂包装会放大单杯成本，必须有足够的体验价值支撑。',
            },
            {
              targetType: 'choice',
              targetId: 'r03-stable',
              relation: 'supports',
              strength: 55,
              explanation: '控制包装复杂度有利于先把主打产品稳定交付。',
            },
          ],
          theoryIds: ['t-product', 't-insight'],
        },
        {
          evidenceId: 'ev-r03-supply',
          title: '供货上限确认',
          fact: '主料常规批次能稳定供应，但季节材料需要提前锁量；临时加单会拉长交期。',
          implication: '地方材料可以成为产品理由，但要把替代方案和备货边界一起写进经营安排。',
          unknown: '还不知道旺季需求会不会超过当前供应上限。',
          cashCostYuan: 1200,
          actionPointCost: 2,
          angle: 'delivery',
          relations: [
            {
              targetType: 'choice',
              targetId: 'r03-local-special',
              relation: 'supports',
              strength: 65,
              explanation: '提前确认来源和批次，才能把地方材料做成可信的产品承诺。',
            },
            {
              targetType: 'choice',
              targetId: 'r03-complex',
              relation: 'warns',
              strength: 50,
              explanation: '步骤和原料都更复杂时，供应波动会更快传到顾客体验上。',
            },
          ],
          theoryIds: ['t-product'],
        },
      ],
      choices: [
        {
          choiceId: 'r03-stable',
          label: '先做一款稳定、好复购的主打茶',
          summary: '先把产品体验做成可持续的习惯。',
          detail: '配方、出杯和包装都控制在团队能稳定完成的范围内，再逐步增加变化。',
          cashCostYuan: 42000,
          actionPointCost: 3,
          durationDays: 10,
          workload: 3,
          primaryBenefit: '交付稳定，容易复购',
          primaryRisk: '第一眼传播不够强',
          evidenceRelations: ['ev-r03-queue'],
          effects: [
            effect('productDelivery', 12, 'immediate', '出杯稳定性提高', 't-product'),
            effect('conversion', 5, 'immediate', '第一次购买更容易发生', 't-product'),
            effect('promiseCredibility', 8, 'delayed', '承诺开始有产品支撑', 't-product'),
          ],
          riskPlanIds: ['risk-r03-supply'],
          conditions: [],
          theoryIds: ['t-product'],
          reportExplanation: '先稳定交付让品牌承诺落到产品流程中，但需要接受声量增长较慢。',
          transferPrompt: '你的产品方案是否超出了实际交付能力？',
          resultArtKey: 'result-r03-stable',
          motionCue: 'tea-pour',
        },
        {
          choiceId: 'r03-complex',
          label: '做一款步骤复杂但很出片的招牌茶',
          summary: '用复杂体验换取记忆点和传播。',
          detail: '加入分层、香气和现场仪式，让顾客愿意拍摄和分享。',
          cashCostYuan: 68000,
          actionPointCost: 4,
          durationDays: 14,
          workload: 5,
          primaryBenefit: '记忆点和传播更强',
          primaryRisk: '高峰交付容易失控',
          evidenceRelations: ['ev-r03-queue', 'ev-r03-price', 'ev-r03-packaging-cost'],
          effects: [
            effect('awareness', 10, 'immediate', '招牌产品获得讨论', 't-product'),
            effect('visualRecognition', 5, 'immediate', '产品画面更容易被记住', 't-product'),
            effect('productDelivery', -10, 'delayed', '复杂流程拖慢交付', 't-product'),
          ],
          riskPlanIds: [],
          conditions: [],
          theoryIds: ['t-product', 't-insight'],
          reportExplanation: '复杂产品可以成为品牌资产，但它把传播机会和交付风险绑在了一起。',
          transferPrompt: '你的产品创意中，哪些部分真正服务品牌，哪些只是增加热闹？',
          resultArtKey: 'result-r03-complex',
          motionCue: 'layered-tea',
        },
        {
          choiceId: 'r03-local-special',
          label: '做一款有地方材料故事的轻量产品',
          summary: '用文化解释和适度溢价建立差异。',
          detail: '使用本地茶材和简洁工艺，把地方故事写进菜单、产品和服务话术。',
          cashCostYuan: 52000,
          actionPointCost: 3,
          durationDays: 12,
          workload: 4,
          primaryBenefit: '文化可信度更强',
          primaryRisk: '故事若不真实会反噬信任',
          evidenceRelations: ['ev-r03-price', 'ev-r03-supply'],
          effects: [
            effect('culturalCredibility', 11, 'immediate', '地方来源说得更清楚', 't-product'),
            effect('differentiation', 8, 'immediate', '与普通茶饮拉开一点距离', 't-product'),
            effect('trust', 4, 'delayed', '顾客逐渐验证故事是否可靠', 't-product'),
          ],
          riskPlanIds: ['risk-r03-supply'],
          conditions: [],
          theoryIds: ['t-product', 't-insight'],
          reportExplanation:
            '地方材料不是自动的文化价值，需要用真实来源、稳定产品和透明价格共同支撑。',
          transferPrompt: '你的地域文化元素是装饰，还是参与了产品价值的形成？',
          resultArtKey: 'result-r03-local',
          motionCue: 'tea-leaf-closeup',
        },
      ],
      riskPlans: [
        {
          riskPlanId: 'risk-r03-supply',
          label: '签一个小批量备用供货协议',
          description: '提前准备一条不追求最低价、但能应急的供应渠道。',
          targetRisk: '原料供应中断',
          cashCostYuan: 6000,
          actionPointCost: 1,
          mitigationRatio: 45,
          theoryIds: ['t-product'],
        },
      ],
      visualTests: [],
      visualRequired: false,
      eventIds: [],
      theoryIds: ['t-product', 't-insight'],
      resultPresentation: {
        resultArtKey: 'result-r03-product',
        motionCue: 'tea-counter',
        characterReactions: [
          {
            characterId: 'character-laozhou',
            text: '产品名字可以很诗意，但装箱单最好还是写清楚。',
            conditions: [],
          },
        ],
      },
    },
    {
      roundId: 'r08',
      chapterId: 'c3',
      title: '设计进入现实',
      timelineLabel: '第5月',
      isKeyRound: true,
      briefing: {
        situation: '设计师递来三套提案：一套很古雅，一套很醒目，一套像街坊手写的招呼。',
        whyNow: 'LOGO和VI马上要进入招牌、杯套、包装和手机头像，今天选的不是一张海报。',
        dilemma: '把三套提案放进店招、杯套和包装后，哪一套先上线？',
        mustComplete: '把选定的视觉方向放进招牌、杯套和包装，找出最先要改的一处。',
        imageKey: 'briefing-r08-visual',
      },
      actionPointBudget: 8,
      stageActions: [
        {
          actionId: 'r08-test-sign',
          actionType: 'test',
          label: '做店招三秒测试',
          description: '把三套方案放进真实街景，观察路人能否认出品类和店名。',
          cashCostYuan: 1500,
          actionPointCost: 1,
          durationDays: 1,
          workload: 1,
          theoryIds: ['t-identity', 't-touchpoint'],
        },
        {
          actionId: 'r08-test-packaging',
          actionType: 'test',
          label: '模拟杯套和包装使用',
          description: '测试沾水、折叠、携带和离开老街后的识别。',
          cashCostYuan: 2800,
          actionPointCost: 2,
          durationDays: 2,
          workload: 2,
          theoryIds: ['t-identity', 't-touchpoint'],
        },
        {
          actionId: 'r08-negotiate-production',
          actionType: 'negotiate',
          label: '确认视觉生产成本',
          description: '把招牌、杯套、包装和社交头像的制作费用一次算清楚。',
          cashCostYuan: 900,
          actionPointCost: 1,
          durationDays: 1,
          workload: 1,
          theoryIds: ['t-identity'],
        },
      ],
      evidence: [
        {
          evidenceId: 'ev-r08-street',
          title: '街景与遮挡观察',
          fact: '窄街中的招牌经常被树、旗幡和人群遮挡；杯子会出现在游客照片和办公室桌面上。',
          implication: '视觉系统不能只在正面大图中好看，还要在小尺寸和非理想视角下识别。',
          unknown: '还不知道三套提案离开老街后是否仍然成立。',
          cashCostYuan: 0,
          actionPointCost: 1,
          angle: 'visual',
          relations: [
            {
              targetType: 'visualSystem',
              targetId: 'v-line',
              relation: 'supports',
              strength: 75,
              explanation: '可缩放系统更适合多触点延展。',
            },
            {
              targetType: 'visualSystem',
              targetId: 'v-symbol',
              relation: 'warns',
              strength: 55,
              explanation: '强地方符号需要测试同街辨识度。',
            },
          ],
          theoryIds: ['t-identity', 't-touchpoint'],
        },
        {
          evidenceId: 'ev-r08-competitor',
          title: '同街视觉并置',
          fact: '周边已有多家店使用山形、徽派屋檐和墨色招牌。',
          implication: '地方符号可以建立联想，也可能让品牌陷入“看起来都差不多”。',
          unknown: '尚未知道顾客会记住哪一个独特元素。',
          cashCostYuan: 0,
          actionPointCost: 1,
          angle: 'competition',
          relations: [
            {
              targetType: 'visualSystem',
              targetId: 'v-symbol',
              relation: 'warns',
              strength: 80,
              explanation: '地方符号方案需要处理同质化风险。',
            },
            {
              targetType: 'visualSystem',
              targetId: 'v-hand',
              relation: 'supports',
              strength: 60,
              explanation: '街坊语气可能成为更具体的关系资产。',
            },
          ],
          theoryIds: ['t-identity', 't-insight'],
        },
        {
          evidenceId: 'ev-r08-touchpoint',
          title: '包装携带记录',
          fact: '顾客最常把杯子带到车站、办公室和朋友家，包装的可读面积比设计稿小很多。',
          implication: '包装不是 LOGO 的复制品，而是一个独立的品牌接触场景。',
          unknown: '还不知道哪种方案能让顾客愿意把包装留下来。',
          cashCostYuan: 1800,
          actionPointCost: 2,
          angle: 'visual',
          relations: [
            {
              targetType: 'visualSystem',
              targetId: 'v-line',
              relation: 'supports',
              strength: 70,
              explanation: '延展性会影响包装离店后的识别。',
            },
            {
              targetType: 'visualSystem',
              targetId: 'v-hand',
              relation: 'supports',
              strength: 65,
              explanation: '手写语气可能提高携带和分享的亲切感。',
            },
          ],
          theoryIds: ['t-identity', 't-touchpoint'],
        },
      ],
      choices: [
        {
          choiceId: 'r08-line',
          label: '选一套能缩小、能延展的识别系统',
          summary: '优先保证招牌、杯套、包装和头像都像同一家店。',
          detail: '不追求单张海报最戏剧化，而是先建立可在不同尺寸和触点中工作的基础规则。',
          cashCostYuan: 56000,
          actionPointCost: 3,
          durationDays: 12,
          workload: 4,
          primaryBenefit: '跨触点一致且耐用',
          primaryRisk: '第一眼戏剧性较弱',
          evidenceRelations: ['ev-r08-street', 'ev-r08-touchpoint'],
          effects: [
            effect('visualRecognition', 10, 'immediate', '识别基础更稳', 't-identity'),
            effect('visualAdaptability', 12, 'immediate', '触点延展能力提高', 't-touchpoint'),
            effect('brandConsistency', 8, 'delayed', '视觉与产品承诺更一致', 't-touchpoint'),
          ],
          riskPlanIds: ['risk-r08-production'],
          conditions: [],
          theoryIds: ['t-identity', 't-touchpoint'],
          reportExplanation: '视觉系统的价值不只在于第一眼好看，还在于能否持续进入真实经营触点。',
          transferPrompt: '你的 LOGO、VI 和包装是否组成一个能工作的系统？',
          visualRouteId: 'v-line',
          resultArtKey: 'result-r08-line',
          motionCue: 'line-extend',
        },
        {
          choiceId: 'r08-symbol',
          label: '选最有地方符号感的方案',
          summary: '让顾客一眼联想到黄山和老街。',
          detail: '强化山形、屋檐和地方色彩，把地域识别放在第一位。',
          cashCostYuan: 48000,
          actionPointCost: 3,
          durationDays: 9,
          workload: 3,
          primaryBenefit: '地域联想建立得快',
          primaryRisk: '和同街品牌撞车',
          evidenceRelations: ['ev-r08-street', 'ev-r08-competitor'],
          effects: [
            effect('culturalCredibility', 8, 'immediate', '地方联想变强', 't-identity'),
            effect('visualRecognition', 10, 'immediate', '街景中更醒目', 't-identity'),
            effect('differentiation', -8, 'delayed', '同质化风险上升', 't-touchpoint'),
          ],
          riskPlanIds: [],
          conditions: [],
          theoryIds: ['t-identity', 't-insight'],
          reportExplanation:
            '地域符号可以帮助快速理解，但必须通过独特组合和触点使用避免变成通用装饰。',
          transferPrompt: '你的地域文化符号是否形成了自己的语法？',
          visualRouteId: 'v-symbol',
          resultArtKey: 'result-r08-symbol',
          motionCue: 'mountain-stamp',
        },
        {
          choiceId: 'r08-hand',
          label: '选像街坊招呼一样的手写系统',
          summary: '用亲切语气建立关系，而不是只靠地方图腾。',
          detail: '让手写字、留言和小图形进入杯套、菜单与社交内容，形成可持续更新的关系表达。',
          cashCostYuan: 39000,
          actionPointCost: 4,
          durationDays: 14,
          workload: 4,
          primaryBenefit: '社区关系和内容延展性强',
          primaryRisk: '规范不清会显得杂乱',
          evidenceRelations: ['ev-r08-competitor', 'ev-r08-touchpoint'],
          effects: [
            effect('trust', 6, 'immediate', '店铺语气更亲近', 't-touchpoint'),
            effect('differentiation', 8, 'immediate', '关系表达形成差异', 't-identity'),
            effect('brandConsistency', -4, 'delayed', '缺乏规则会造成视觉松散', 't-touchpoint'),
          ],
          riskPlanIds: ['risk-r08-production'],
          conditions: [],
          theoryIds: ['t-identity', 't-touchpoint'],
          reportExplanation: '亲切感本身不是系统，需要用清晰的字形、色彩和应用边界把自由表达托住。',
          transferPrompt: '你的 IP 或手写元素承担了什么品牌任务？',
          visualRouteId: 'v-hand',
          resultArtKey: 'result-r08-hand',
          motionCue: 'handwrite-loop',
        },
      ],
      riskPlans: [
        {
          riskPlanId: 'risk-r08-production',
          label: '先做一页触点规范',
          description: '明确字号、留白、最小尺寸和不可滥用的视觉边界。',
          targetRisk: '视觉落地失控',
          cashCostYuan: 6500,
          actionPointCost: 1,
          mitigationRatio: 50,
          theoryIds: ['t-identity', 't-touchpoint'],
        },
      ],
      visualTests: [
        {
          testId: 'r08-sign-3-second',
          title: '24 px 缩小测试',
          prompt: '把主标识缩到 24 px 高，顾客还能看出它是谁吗？',
          theoryIds: ['t-identity'],
        },
        {
          testId: 'r08-mobile-shrink',
          title: '黑白打印测试',
          prompt: '去掉颜色以后，主次关系和识别线索还成立吗？',
          theoryIds: ['t-identity', 't-touchpoint'],
        },
        {
          testId: 'r08-packaging-stress',
          title: '35% 遮挡测试',
          prompt: '顾客拿杯子时挡住标识约三分之一，剩下的线索够不够？',
          theoryIds: ['t-touchpoint'],
        },
      ],
      visualRequired: true,
      eventIds: [],
      theoryIds: ['t-identity', 't-touchpoint', 't-insight'],
      resultPresentation: {
        resultArtKey: 'result-r08-visual',
        motionCue: 'touchpoint-pan',
        characterReactions: [
          {
            characterId: 'character-xiaoman',
            text: '今天选的不是一张图，是以后每个触点都要遵守的一套关系。',
            conditions: [],
          },
          {
            characterId: 'character-ahe',
            text: '杯子拿出老街以后还像你的，这才算真的上线。',
            conditions: [{ type: 'visual_was', visualId: 'v-line' }],
          },
        ],
      },
    },
    {
      roundId: 'r11',
      chapterId: 'c4',
      title: '火了以后全是事',
      timelineLabel: '第9—10月',
      isKeyRound: false,
      briefing: {
        situation: '一条短视频让店门口排起了队，平台来谈合作，老客却说自己进不去了。',
        whyNow: '增长会把品牌的优势和漏洞一起放大，现在必须决定扩张速度。',
        dilemma: '趁热扩大线上渠道，还是先把老客和交付能力稳住？',
        mustComplete: '订单变多了，先决定保护老客体验还是扩大新客入口。',
        imageKey: 'briefing-r11-growth',
      },
      actionPointBudget: 8,
      stageActions: [
        {
          actionId: 'r11-audit-capacity',
          actionType: 'research',
          label: '盘点供应和服务能力',
          description: '把原料、培训、出杯和门店动线的上限列出来。',
          cashCostYuan: 800,
          actionPointCost: 1,
          durationDays: 1,
          workload: 1,
          theoryIds: ['t-growth'],
          revealsEvidenceIds: ['ev-r11-capacity', 'ev-r11-loyalty'],
        },
        {
          actionId: 'r11-test-delivery',
          actionType: 'test',
          label: '做一次高峰压力测试',
          description: '模拟短时间订单暴增，观察队伍、产品和团队如何反应。',
          cashCostYuan: 4200,
          actionPointCost: 2,
          durationDays: 3,
          workload: 3,
          theoryIds: ['t-growth', 't-product'],
          revealsEvidenceIds: ['ev-r11-delivery'],
        },
        {
          actionId: 'r11-negotiate-platform',
          actionType: 'negotiate',
          label: '先谈合作边界',
          description: '和平台确认流量、抽成、配送和品牌关系的边界。',
          cashCostYuan: 1500,
          actionPointCost: 2,
          durationDays: 2,
          workload: 2,
          theoryIds: ['t-growth'],
          revealsEvidenceIds: ['ev-r11-platform-terms'],
        },
      ],
      evidence: [
        {
          evidenceId: 'ev-r11-capacity',
          title: '供应和服务盘点',
          fact: '原料供应可以支撑约1.5倍订单，但培训、排班和店内动线还没有准备好。',
          implication: '增长不是单纯增加曝光，必须先看组织是否能交付。',
          unknown: '还不知道平台订单会在什么时间段集中涌入。',
          cashCostYuan: 0,
          actionPointCost: 1,
          angle: 'delivery',
          relations: [
            {
              targetType: 'choice',
              targetId: 'r11-platform',
              relation: 'warns',
              strength: 80,
              explanation: '平台增长会直接放大交付压力。',
            },
            {
              targetType: 'choice',
              targetId: 'r11-steady',
              relation: 'supports',
              strength: 70,
              explanation: '先稳住组织能力更符合当前上限。',
            },
          ],
          theoryIds: ['t-growth', 't-product'],
        },
        {
          evidenceId: 'ev-r11-loyalty',
          title: '高峰期老客反馈',
          fact: '排队时仍在回来的老客里，有三成说“感觉自己不再被看见”。',
          implication: '增长如果损害原有关系，品牌资产会出现隐性流失。',
          unknown: '尚未知道老客是否愿意接受预约、限量或错峰服务。',
          cashCostYuan: 1200,
          actionPointCost: 1,
          angle: 'customer',
          relations: [
            {
              targetType: 'choice',
              targetId: 'r11-steady',
              relation: 'supports',
              strength: 75,
              explanation: '老客反馈支持先修复关系和服务体验。',
            },
          ],
          theoryIds: ['t-growth'],
        },
        {
          evidenceId: 'ev-r11-delivery',
          title: '高峰压力测试记录',
          fact: '订单在二十分钟内翻倍时，出杯、打包和确认信息会同时堵住；错单从第二波订单开始增加。',
          implication: '增长不是只多接几单，必须先把每个交接点的上限和负责人说清楚。',
          unknown: '还不知道平台配送高峰会不会和门店高峰重叠。',
          cashCostYuan: 4200,
          actionPointCost: 2,
          angle: 'delivery',
          relations: [
            {
              targetType: 'choice',
              targetId: 'r11-platform',
              relation: 'warns',
              strength: 85,
              explanation: '订单同时涌入会让现有交付环节先失控。',
            },
            {
              targetType: 'choice',
              targetId: 'r11-steady',
              relation: 'supports',
              strength: 60,
              explanation: '先设上限和错峰，能为交付修复留下空间。',
            },
          ],
          theoryIds: ['t-growth', 't-product'],
        },
        {
          evidenceId: 'ev-r11-platform-terms',
          title: '平台合作边界',
          fact: '平台能带来曝光和配送订单，但抽成、活动折扣和高峰配送规则都会直接影响单杯利润与顾客等待。',
          implication:
            '合作不是只看订单量，还要明确谁承担折扣、延误和客诉，避免品牌承诺被平台节奏带走。',
          unknown: '还不知道活动峰值会不会超过门店与供应链的共同上限。',
          cashCostYuan: 1500,
          actionPointCost: 2,
          angle: 'cost',
          relations: [
            {
              targetType: 'choice',
              targetId: 'r11-platform',
              relation: 'warns',
              strength: 70,
              explanation: '平台订单增加的同时，也会放大抽成、折扣和配送等待的压力。',
            },
            {
              targetType: 'choice',
              targetId: 'r11-steady',
              relation: 'context',
              strength: 50,
              explanation: '先把合作边界写清，可以把增长留到交付准备好以后。',
            },
          ],
          theoryIds: ['t-growth'],
        },
      ],
      choices: [
        {
          choiceId: 'r11-platform',
          label: '趁热扩大线上渠道',
          summary: '把短视频热度尽快转成订单和知名度。',
          detail: '接受平台合作和更大的投放，把更多顾客带到线上和线下。',
          cashCostYuan: 72000,
          actionPointCost: 4,
          durationDays: 30,
          workload: 5,
          primaryBenefit: '声量和订单快速增长',
          primaryRisk: '平台依赖和服务失控',
          evidenceRelations: ['ev-r11-capacity', 'ev-r11-delivery', 'ev-r11-platform-terms'],
          effects: [
            effect('awareness', 15, 'immediate', '声量迅速放大', 't-growth'),
            effect('conversion', 8, 'immediate', '订单开始增加', 't-growth'),
            effect('channelDependence', 12, 'delayed', '平台依赖加深', 't-growth'),
            effect('orgCapacity', -10, 'delayed', '团队承压', 't-growth'),
          ],
          riskPlanIds: ['risk-r11-delivery'],
          conditions: [],
          theoryIds: ['t-growth', 't-product'],
          reportExplanation: '增长选择把品牌推得更远，也把交付和渠道依赖问题暴露给更多人。',
          transferPrompt: '你的品牌传播方案能否被现有系统承接？',
          resultArtKey: 'result-r11-platform',
          motionCue: 'notification-storm',
        },
        {
          choiceId: 'r11-steady',
          label: '先限量，把老客体验稳住',
          summary: '暂时放慢扩张，修复关系和交付能力。',
          detail: '设置每日上限、错峰服务和老客预约，把增长机会留到团队准备好以后。',
          cashCostYuan: 26000,
          actionPointCost: 3,
          durationDays: 21,
          workload: 3,
          primaryBenefit: '信任和组织能力同步积累',
          primaryRisk: '错过部分热度',
          evidenceRelations: ['ev-r11-capacity', 'ev-r11-loyalty'],
          effects: [
            effect('trust', 8, 'immediate', '老客感到被看见', 't-growth'),
            effect('orgCapacity', 8, 'delayed', '组织能力得到缓冲', 't-growth'),
            effect('loyalty', 8, 'delayed', '社区关系更稳', 't-growth'),
            effect('awareness', -4, 'immediate', '扩散速度放慢', 't-growth'),
          ],
          riskPlanIds: ['risk-r11-delivery'],
          conditions: [],
          theoryIds: ['t-growth', 't-product'],
          reportExplanation: '限制增长不是拒绝发展，而是让品牌承诺和组织能力先重新对齐。',
          transferPrompt: '什么时候“少接一点”反而是在保护品牌？',
          resultArtKey: 'result-r11-steady',
          motionCue: 'queue-breath',
        },
        {
          choiceId: 'r11-community',
          label: '把增长变成社区会员机制',
          summary: '不追求最大流量，优先经营可持续的关系网络。',
          detail: '用预约、分享和线下活动把熟客、附近商户和稳定游客组织起来。',
          cashCostYuan: 38000,
          actionPointCost: 4,
          durationDays: 25,
          workload: 4,
          primaryBenefit: '关系质量和复购提高',
          primaryRisk: '规模扩张速度较慢',
          evidenceRelations: ['ev-r11-loyalty'],
          effects: [
            effect('loyalty', 10, 'immediate', '熟客关系被重新组织', 't-growth'),
            effect('trust', 6, 'immediate', '顾客更愿意参与', 't-growth'),
            effect('awareness', 4, 'delayed', '口碑传播逐步扩大', 't-growth'),
          ],
          riskPlanIds: [],
          conditions: [],
          theoryIds: ['t-growth'],
          reportExplanation: '社区机制牺牲了部分即时规模，换取更稳定的顾客关系和品牌忠诚。',
          transferPrompt: '你的品牌如何让顾客从一次购买变成持续关系？',
          resultArtKey: 'result-r11-community',
          motionCue: 'stamp-card',
        },
      ],
      riskPlans: [
        {
          riskPlanId: 'risk-r11-delivery',
          label: '先做高峰交付预案',
          description: '提前设置订单上限、替代产品和顾客告知方式。',
          targetRisk: '增长超过交付能力',
          cashCostYuan: 8500,
          actionPointCost: 1,
          mitigationRatio: 55,
          theoryIds: ['t-growth', 't-product'],
        },
      ],
      visualTests: [],
      visualRequired: false,
      eventIds: [],
      theoryIds: ['t-growth', 't-product'],
      resultPresentation: {
        resultArtKey: 'result-r11-growth',
        motionCue: 'street-queue',
        characterReactions: [
          {
            characterId: 'character-ahe',
            text: '火是好事，但别让火把菜单、团队和老客一起烤糊了。',
            conditions: [],
          },
        ],
      },
    },
  ],
  visualSystems: [
    {
      visualId: 'v-line',
      name: '一笔成街',
      description: '用连续线条和清晰比例建立可缩放、可延展的识别系统。',
      touchpoints: [
        'storefront',
        'side-sign',
        'door-info',
        'menu-board',
        'order-card',
        'receipt',
        'cup',
        'cup-sleeve',
        'packaging',
        'avatar',
      ],
      matchFactors: {
        customerFit: 78,
        positionFit: 82,
        productFit: 78,
        cultureFit: 68,
        priceFit: 75,
        touchpointFit: 92,
      },
    },
    {
      visualId: 'v-symbol',
      name: '山影入杯',
      description: '把山形和茶饮容器结合，第一眼地域联想很强。',
      touchpoints: [
        'storefront',
        'side-sign',
        'door-info',
        'menu-board',
        'order-card',
        'receipt',
        'cup',
        'cup-sleeve',
        'packaging',
        'avatar',
      ],
      matchFactors: {
        customerFit: 75,
        positionFit: 70,
        productFit: 82,
        cultureFit: 90,
        priceFit: 70,
        touchpointFit: 62,
      },
    },
    {
      visualId: 'v-hand',
      name: '茶友阿街 IP',
      description: '让一位固定角色承担杯套、贴纸和互动提醒；亲切，但需要持续维护角色规则。',
      touchpoints: [
        'storefront',
        'side-sign',
        'door-info',
        'menu-board',
        'order-card',
        'receipt',
        'cup',
        'cup-sleeve',
        'packaging',
        'avatar',
      ],
      matchFactors: {
        customerFit: 88,
        positionFit: 76,
        productFit: 72,
        cultureFit: 82,
        priceFit: 84,
        touchpointFit: 78,
      },
    },
  ],
  achievements: [
    {
      achievementId: 'a-evidence-first',
      title: '看完客流再定方向',
      description: '你把客流观察带进了第一轮的经营判断。',
      conditions: [{ type: 'evidence_viewed', evidenceId: 'ev-r01-footfall' }],
      reasonTemplate: '你看见了居民和游客出现的时间不同，再决定先服务谁。',
    },
    {
      achievementId: 'a-touchpoint-system',
      title: '换个地方也认得出',
      description: '你检查了视觉放到真实触点后是否仍然清楚。',
      conditions: [{ type: 'visual_was', visualId: 'v-line' }],
      reasonTemplate: '你开始把视觉当作系统，而不是单张效果图。',
    },
  ],
  endings: [
    {
      endingId: 'e-community-route',
      title: '社区关系型品牌',
      description: '规模不喧闹，但顾客愿意带朋友回来。',
      conditions: [{ type: 'metric_at_least', key: 'loyalty', value: 55 }],
      minimumRoundsRequired: 3,
      minimumDimensionsRequired: 2,
    },
    {
      endingId: 'e-visual-route',
      title: '视觉驱动型品牌',
      description: '视觉在真实触点中形成了辨识度，也承担了传播任务。',
      conditions: [{ type: 'visual_was', visualId: 'v-line' }],
      minimumRoundsRequired: 3,
      minimumDimensionsRequired: 2,
    },
    {
      endingId: 'e-growth-route',
      title: '平台增长型品牌',
      description: '品牌获得了更大声量，也必须持续管理增长带来的压力。',
      conditions: [{ type: 'choice_was', choiceId: 'r11-platform' }],
      minimumRoundsRequired: 3,
      minimumDimensionsRequired: 2,
    },
    {
      endingId: 'e-still-learning',
      title: '一家还在学习的店',
      description:
        '你把一年经营走完了。还有不少地方没有站稳，但每次取舍都留下了下一步可以继续验证的线索。',
      conditions: [],
      minimumRoundsRequired: 3,
      minimumDimensionsRequired: 2,
      fallback: true,
    },
  ],
});
